name:                bigball
version:             0.1.0.0
github:              "jecaro/bigball"
license:             BSD3
author:              "Jean-Charles Quillet"
maintainer:          "jeancharles.quillet@gmail.com"
copyright:           "2020 Jean-Charles Quillet"

extra-source-files:
- README.md
- data/project.html

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jecaro/bigball#readme>

dependencies:
- array
- base >= 4.7 && < 5
- containers
- exceptions
- hspec
- file-embed
- lucid
- optparse-applicative
- parsec
- path
- path-io
- relude
- text

library:
  source-dirs: src

executables:
  bigball:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - bigball

tests:
  bigball-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - bigball

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
